### ISSUE TITLE
IE8 compatibility problems

### ISSUE THREAD

**Issue by tlewis17** [pseudosavant/psQuery#1]
The reason I am looking to use this is because it contains the things I need for a client side data retrieval API I am creating. And it is much smaller than JQuery 1.x. Also IE8 compatibility is a big thing for us. 

I have run into 2 problems and 1 minor annoyance in testing.

In IE8 Compatibility mode:
Array doesn't have a forEach method. This can be resolved by adding the following to the top of the script:

```
if (!Array.prototype.forEach)
{
  Array.prototype.forEach = function(fun /*, thisArg */)
  {
    "use strict";

    if (this === void 0 || this === null)
      throw new TypeError();

    var t = Object(this);
    var len = t.length >>> 0;
    if (typeof fun !== "function")
      throw new TypeError();

    var thisArg = arguments.length >= 2 ? arguments[1] : void 0;
    for (var i = 0; i < len; i++)
    {
      if (i in t)
        fun.call(thisArg, t[i], i, t);
    }
  };
};
```

As per:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/forEach?redirectlocale=en-US&redirectslug=JavaScript%2FReference%2FGlobal_Objects%2FArray%2FforEach

In IE8 Compatibility mode:
There is no addEventListener. According to:
https://developer.mozilla.org/en-US/docs/Web/API/EventTarget.addEventListener
There is a way to add a compatibility section to add that just like what was done for Array, but I cannot seem to get it to work if I add that to the top of the script. The other alternative is:

```
if (el.addEventListener) {
  el.addEventListener('click', modifyText, false); 
} else if (el.attachEvent)  {
  el.attachEvent('onclick', modifyText);
}
```

Minor Annoyance:
After every request, the results are output by console.log. Is that necessary? Seems like just some debugging code.

**Comment by pseudosavant** [comment]
@snoopyowns Sorry I missed this issue you opened up. I never got notified about it.

Regarding the IE8 issues. I'm actually only targeting >= 9 for IE. I saw there was a typo in my repo that said IE8 but clearly I wouldn't be using `forEach` and only `addEventListener` if that was the case. Both of those can be shimmed (like the `forEach` code you shared) however to give you IE8 support. I'd rather not have IE8 directly in the main file but I wouldn't be opposed to having a 'oldIE' file that would extend support back to IE8 and maybe even IE7. Any other IE8 issues you have noticed?

I should point out that the event system is very basic right now. I have plans to extend the system to use event delegation instead of direct event binding. I just haven't gotten around to it yet.

psQuery is very much a WIP and so that is why there was an errant console.log in there. I have removed that from trunk.

**Comment by tlewis17** [comment]
Thanks for the response. >= IE9 makes sense. IE8 only accounts for 2.4% of browsers and IE7 is 0.3%. In my opinion, it isn't even worth trying to support that old of browsers.
http://www.w3schools.com/browsers/browsers_explorer.asp

I didn't have any other issues. IE9 worked just fine but due to the repository saying IE8 I thought it should work there too. The console.log is something I use a lot myself, so I know how it is to miss one or two of them.
